CREATE TABLE '3YP_ITEMS'( ID bigint(20) NOT NULL, 
NAME char(60) COLLATE utf8_unicode_ci NOT NULL, 
PRICE decimal(19,4) NOT NULL,
QUANTITY INTEGER unsigned NOT NULL,
STOCK_COUNT_ON boolean(1) NOT NULL, 
NEED_AGE_CHECK boolean(1) DEFAULT 0 NOT NULL ,
FOOD_OR_DRINK enum(FOOD,DRINK,,) COLLATE utf8_unicode_ci NOT NULL )