/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.MainMenu;

import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author mbbx9mg3
 */
public class BarTabDialogSelect extends javax.swing.JDialog {

    public int numberOfTabs;
    /**
     * Creates new form BarTabDialogSelect
     * @param parent
     * @param modal
     */
    public BarTabDialogSelect(Dialog parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();        
    }
    
    public void setButtons(ArrayList<JButton> jBs)
    {
        System.out.println("set buttons: " + jBs.size() + " buttons");
        numberOfTabs = jBs.size();
        if (jBs.size() <= 0)
            return;


        this.getContentPane().removeAll();
        
        for (JButton jb : jBs)
        {
            final BarTabDialogSelect parent = this;
            jb.addActionListener(new ActionListener()
            {

                @Override
                public void actionPerformed(ActionEvent e) {
                    parent.dispose();
                }
            });
            this.getContentPane().add(jb);
            this.pack();
            this.repaint();

            this.doLayout();
            this.revalidate();
            this.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bar Tabs");
        getContentPane().setLayout(new java.awt.GridLayout(0, 5));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


}
