/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.MainMenu;

import Client.TillClient;
import Message.Request.Request;
import Message.Request.TabRequest;
import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author mbbx9mg3
 */
public class BarTabDialogSelect extends javax.swing.JDialog {

    public int numberOfTabs;
    private boolean tabReceived;
    
    /**
     * Creates new form BarTabDialogSelect
     * @param parent
     * @param modal
     */
    public BarTabDialogSelect(Dialog parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();      
        this.tabReceived = false;
    }
    
    public void setButtons(HashMap<JButton, Integer> jBs)
    {
        System.out.println("set buttons: " + jBs.size() + " buttons");
        numberOfTabs = jBs.size();
        if (jBs.size() <= 0)
            return;

        this.getContentPane().removeAll();
        final BarTabDialogSelect parent = this;       
        for (JButton jb : jBs.keySet())
        {
            final int tableNum = jBs.get(jb);
            jb.addActionListener(new ActionListener()
            {
                @Override
                public void actionPerformed(ActionEvent e) 
                {
                    TillMenu menuParent = (TillMenu)parent.getParent();
                    TillClient parentClient = (TillClient)menuParent.parentClient;
                    try 
                    {
                        TabRequest req = new TabRequest(                
                            InetAddress.getByName(
                                parentClient.client.getLocalAddress().getHostName()),
                            InetAddress.getByName(
                                parentClient.serverAddress.getHostName()),
                              
                            Message.Message.generateRequestID(), 
                            Request.RequestType.TAB,
                              tableNum);
                        parentClient.getOutputStream().writeObject(req);
                        
                        synchronized(parentClient.getLock())
                        {
                    
                            while(menuParent.selectorFrame.tabReceived == false)
                                parentClient.getLock().wait();
                        } // sync
                        
                        
                    } 
                    catch (UnknownHostException ex) 
                    {
                        Logger.getLogger(BarTabDialogSelect.class.getName()).log(Level.SEVERE, null, ex);
                    } 
                    catch (IOException | InterruptedException ex) 
                    {
                        Logger.getLogger(BarTabDialogSelect.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    parent.dispose();
                }
            }); // actionListener
            this.getContentPane().add(jb);         
        } // for
        JButton cancelButton = new JButton("Cancel");
        cancelButton.addActionListener(new ActionListener()
        {

                @Override
                public void actionPerformed(ActionEvent e) {
                    parent.dispose();
                }
        });;
        this.getContentPane().add(cancelButton);
        this.pack();
        this.doLayout();
        this.revalidate();
        this.repaint();
    }
    
    public boolean getTabReceived()
    {
        return tabReceived;
    }
    
    public void setTabReceived(boolean tabRecevied)
    {
        this.tabReceived = tabRecevied;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bar Tabs");
        getContentPane().setLayout(new java.awt.GridLayout(0, 5));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


}
