/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import Client.MainMenu.TillMenu;
import static Message.Message.generateRequestID;
import Message.Request.LeaveRequest;
import Message.Request.Request;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author mbbx9mg3
 */
public class TillGUI extends javax.swing.JFrame implements ActionListener
{

    private final TillClient parent;
    private final TillMenu menu;
    /**
     * Creates new form TillClient
     * @param parent The parent client of the GUI
     */
    public TillGUI(TillClient parent) 
    {
        super();
        this.parent = parent;
        this.menu = TillMenu.makeMenu(parent, 
                null, null, parent.getOutputStream(),  this);
        initComponents();
        
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startClientButton = new javax.swing.JButton();
        changeLabel = new javax.swing.JLabel();
        changeOutputLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        startClientButton.setText("Start Till Client");

        changeLabel.setText("Change:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(startClientButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(changeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(changeOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(startClientButton)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeLabel)
                    .addComponent(changeOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        startClientButton.addActionListener(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       
        int confirm = JOptionPane.showOptionDialog(null, 
            "Are You Sure to Close Application?", "Exit Confirmation", 
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, 
            null, null, null);
                
        if (confirm == 0) 
        { 
            try 
            {
                // TODO add your handling code here:
                menu.con.close();
                LeaveRequest leaveRequest = new LeaveRequest(
                    InetAddress.getByName(
                        parent.client.
                    getLocalAddress().getHostName()),
                    InetAddress.getByName(
                        parent.serverAddress.getHostName()),
                    generateRequestID(),
                    Request.RequestType.LEAVE);
                parent.getOutputStream().writeObject(leaveRequest);
            } catch (SQLException ex) {
                Logger.getLogger(TillGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnknownHostException ex) {
                Logger.getLogger(TillGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(TillGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel changeLabel;
    private javax.swing.JLabel changeOutputLabel;
    private javax.swing.JButton startClientButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae)
    {
        if (ae.getSource() == this.startClientButton)
        {
                menu.setVisible(true);
        } // if      
    } // actionPerformed
    
    public JLabel getChangeOutputLabel()
    {
        return changeOutputLabel;
    }
    
    public TillMenu getMenu()
    {
        return menu;
    }

}

